[theme]
base = "dark"
primaryColor = "#ff4b4b"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#ffffff"
font = "sans serif"

[server]
port = 5000
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false
